### ISSUE TITLE
TypeError for path

### ISSUE THREAD

**Issue by Yayutan** [melih-unsal/DemoGPT#6]
**Describe the bug**
I am using DemoGPT on MAC, and ran into TypeError once I submitted.

**To Reproduce**
1. On terminal, run app with command `streamlit run app.py`
2. Click on the example Language Translator
3. Click submit button

**Error Message**
`
Language Translator 📝
2023-07-03 17:26:34.783 Uncaught app exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/Users/mchuang/Desktop/Testing tools/DemoGPT/src/prompt_based/app.py", line 67, in <module>
    for data in generate_response(demo_idea):
  File "/Users/mchuang/Desktop/Testing tools/DemoGPT/src/prompt_based/app.py", line 16, in generate_response
    for data in agent(txt,num_of_iterations):
  File "/Users/mchuang/Desktop/Testing tools/DemoGPT/src/prompt_based/model.py", line 69, in __call__
    response, error = self.run_python(total_code)
  File "/Users/mchuang/Desktop/Testing tools/DemoGPT/src/prompt_based/model.py", line 35, in run_python
    process = subprocess.Popen([python_path,tmp.name], env=environmental_variables,stdout=PIPE, stderr=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1717, in _execute_child
    and os.path.dirname(executable)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

**Screenshots**
<img width="751" alt="image" src="https://github.com/melih-unsal/DemoGPT/assets/25274391/1fd0cbd5-a9ba-4e0f-a576-eb9806724799">

**Desktop (please complete the following information):**
 - OS: macOS Monterey ver.12.3.1
 - Browser: Chrome
 - Version: 114.0.5735.106

**Comment by melih-unsal** [comment]
Hey @Yayutan ,

Thank you for your detailed report and for bringing this issue to our attention. We sincerely apologize for any inconvenience caused. It appears that the issue was related to the "which" command runs in the macOS operating system, as you rightly pointed out.

I'm glad to inform you that we've pushed a new update to the repository that should resolve the issue. You should now be able to run the Streamlit app without encountering this problem.

Please update your local copy of the repository and retry running the Streamlit app. If you encounter any further issues, don't hesitate to report them. Your feedback is highly appreciated and helps us improve the overall user experience.

Thank you for your support and contribution to DemoGPT.

Best,
Melih
